// <auto-generated />
namespace SistemZaZakazuvanje.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class in12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(in12));
        
        string IMigrationMetadata.Id
        {
            get { return "202207141258470_in12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
